language: vi

pipeline:
#- name: VietnameseTokenizer
- name: HFTransformersNLP
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 40
  use_masked_language_model: True
  embedding_dimension: 30
  connection_density: 0.7
  model_confidence: softmax
  constrain_similarities: True

- name: FallbackClassifier
  threshold: 0.5


policies:

  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: RulePolicy
